@startuml

Client1 -> Serveur: Authentification
Serveur -> Client1: OK
Client2 -> Serveur: Authentification
Serveur -> Client2: OK
loop communication
  Client1 -> Serveur: Envoi d'un message
  Serveur -> Client2: Relai du message (thread1)
  Client2 -> Serveur: Message reçu
  Client2 -> Serveur: Envoi d'un message
  Serveur -> Client1: Relai du message (thread2)
  Client1 -> Serveur: Message reçu
  alt commande "/mp [pseudonyme] [message]"
    Client1 -> Serveur: Envoi d'un message privé
    Serveur -> Client2: Relai du message privé
    Client2 -> Serveur: Message reçu
  end
  alt commande "/fin"
    Serveur -> Client1: Arrêt communication
    Serveur -> Client2: Arrêt communication
  end
  alt ctrl+c serveur
    Serveur -> Client1: Fermeture serveur
    Serveur -> Client2 : Fermeture serveur
  end
  alt ctrl+c client1
    Client1 -> Serveur: Arrêt communication
    Client1 -> Client2: Arrêt communication
  end
  alt commande "/manuel"
    Serveur -> Client1: Envoi fichier texte
  end
end
@enduml